name: online_courses
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.0
  cupertino_icons: ^1.0.8
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.2.0
  cloud_firestore: ^5.6.12
  firebase_core: ^3.15.2
  http: ^1.4.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
