// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArlJlPScyqJ1ekCx56l6AyCt1PO8JcVvc',
    appId: '1:650901453856:web:df45b3c506a2b3b55bd045',
    messagingSenderId: '650901453856',
    projectId: 'flutter--online-courses',
    authDomain: 'flutter--online-courses.firebaseapp.com',
    storageBucket: 'flutter--online-courses.firebasestorage.app',
    measurementId: 'G-EDKDWQPVGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeyf8e_l6awj5CGREyoZo-EkfvrsEwoG0',
    appId: '1:650901453856:android:e9e70744e178ce9e5bd045',
    messagingSenderId: '650901453856',
    projectId: 'flutter--online-courses',
    storageBucket: 'flutter--online-courses.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbRc5kpcQBi3-1x7kpG9UszYPXfHFHeh0',
    appId: '1:650901453856:ios:51f57bd8b2d9d2f75bd045',
    messagingSenderId: '650901453856',
    projectId: 'flutter--online-courses',
    storageBucket: 'flutter--online-courses.firebasestorage.app',
    iosBundleId: 'com.example.onlineCourses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbRc5kpcQBi3-1x7kpG9UszYPXfHFHeh0',
    appId: '1:650901453856:ios:51f57bd8b2d9d2f75bd045',
    messagingSenderId: '650901453856',
    projectId: 'flutter--online-courses',
    storageBucket: 'flutter--online-courses.firebasestorage.app',
    iosBundleId: 'com.example.onlineCourses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArlJlPScyqJ1ekCx56l6AyCt1PO8JcVvc',
    appId: '1:650901453856:web:63ea64052f05da265bd045',
    messagingSenderId: '650901453856',
    projectId: 'flutter--online-courses',
    authDomain: 'flutter--online-courses.firebaseapp.com',
    storageBucket: 'flutter--online-courses.firebasestorage.app',
    measurementId: 'G-FNJXHYPWYZ',
  );
}
